export const FETCH_DOCTOR_REQUEST = "FETCH_DOCTOR_REQUEST";
export const FETCH_DOCTOR_SUCCEESS = "FETCH_DOCTOR_SUCCEESS";
export const FETCH_DOCTOR_ERROR = "FETCH_DOCTOR_ERROR";
export const UPDATE_FILTER_REQUEST = "UPDATE_FILTER_REQUEST";